# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/pdx245/setup-makefiles.sh
BOARD_SYSTEM_EXT_SEPOLICY_DIRS += system/sepolicy/private/system_ext
BOARD_VENDOR_SEPOLICY_DIRS += vendor/sony/pdx245/sepolicy